name: Scraper Vuelos - Test

on:
  workflow_dispatch:   # Permite ejecutar manualmente desde GitHub

jobs:
  run-scraper:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Instalar dependencias
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Instalar Firefox
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox

      - name: Instalar Geckodriver
        run: |
          GECKO_VERSION="v0.34.0"
          wget -q "https://github.com/mozilla/geckodriver/releases/download/$GECKO_VERSION/geckodriver-$GECKO_VERSION-linux64.tar.gz"
          tar -xvzf "geckodriver-$GECKO_VERSION-linux64.tar.gz"
          chmod +x geckodriver
          sudo mv geckodriver /usr/local/bin/

      - name: Ejecutar scraper y comprobar archivos
        run: |
          echo "📌 Iniciando scraper..."
          python Proyecto_aereo.py
          echo "📌 Comprobando archivos generados..."
          if [ -d "data/$(date +'%Y-%m-%d')" ]; then
              ls -l data/$(date +'%Y-%m-%d')
          else
              echo "⚠️ Carpeta de hoy no encontrada"
          fi
